### ISSUE TITLE
Messes up natives and some skin related things

### ISSUE THREAD

**Issue by kloudyzxc** [JaredScar/ResourceEventScrambler#4]
In my case it messes up "Speed" for example is SetVehicleForwardSpeed it will change into SetVehicleForwardSTJULlPyqvd and in skinchanger it changes helmet, mask, and glasses into wCLqaqYmi, yGjFtpfeM, bFztZeMdk

**Comment by nick-perry14** [comment]
This is not an issue, this is more of TERRIBLE coding practices of the other resources.  For example, if the resource has an event called "sit", then ANY TIME that the scrambler will replace a match with that.  For example, position would be changed to posyGjFtpfeMon because of it.  The best way to fix this is to find the offending one-word resources and use a prefix (such as esxskin:hat).  This will prevent incidental replacements.
